"""added quntity

Revision ID: 179e13d86ae
Revises: 39061342b5e1
Create Date: 2014-06-20 23:30:55.334000

"""

# revision identifiers, used by Alembic.
revision = '179e13d86ae'
down_revision = '39061342b5e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('quantity', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'quantity')
    ### end Alembic commands ###
