"""empty message

Revision ID: 36e7a6955773
Revises: None
Create Date: 2014-06-13 17:14:44.922000

"""

# revision identifiers, used by Alembic.
revision = '36e7a6955773'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('money', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('portfolio')
    ### end Alembic commands ###
