"""empty message

Revision ID: 3b197e11aaa1
Revises: 5a05e7b66851
Create Date: 2014-06-15 17:19:12.508000

"""

# revision identifiers, used by Alembic.
revision = '3b197e11aaa1'
down_revision = '5a05e7b66851'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('portfolio', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'portfolio')
    ### end Alembic commands ###
