"""empty message

Revision ID: 3ddf8cceb21c
Revises: None
Create Date: 2014-06-12 22:39:51.800000

"""

# revision identifiers, used by Alembic.
revision = '3ddf8cceb21c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
