"""empty message

Revision ID: 4fedeeb1146e
Revises: 36e7a6955773
Create Date: 2014-06-13 20:16:22.791000

"""

# revision identifiers, used by Alembic.
revision = '4fedeeb1146e'
down_revision = '36e7a6955773'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('change', sa.Float(), nullable=True))
    op.add_column('stock', sa.Column('change_p', sa.Float(), nullable=True))
    op.add_column('stock', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('stock', sa.Column('open', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'open')
    op.drop_column('stock', 'date')
    op.drop_column('stock', 'change_p')
    op.drop_column('stock', 'change')
    ### end Alembic commands ###
