"""empty message

Revision ID: 570b89e6c348
Revises: 3ddf8cceb21c
Create Date: 2014-06-12 22:51:59.992000

"""

# revision identifiers, used by Alembic.
revision = '570b89e6c348'
down_revision = '3ddf8cceb21c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money',
    sa.Column('money', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('money')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=400), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('money')
    ### end Alembic commands ###
