"""empty message

Revision ID: 5a05e7b66851
Revises: 4fedeeb1146e
Create Date: 2014-06-13 20:56:02.212000

"""

# revision identifiers, used by Alembic.
revision = '5a05e7b66851'
down_revision = '4fedeeb1146e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'portfolio')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('portfolio', mysql.INTEGER(display_width=11), nullable=True))
    ### end Alembic commands ###
